### ISSUE TITLE
dynamic loadbalancer ip reference

### ISSUE THREAD

**Issue by derrabauke** [displague/terraform-linode-lke-addons#1]
Hi @displague, 

I'm trying to setup a cluster with a free domain service like [nip.io](https://nip.io), therefore I have to reference the load-balancer IP in the ingress-controller manifest (host variable).

My guess was something like this:
```terraform
data "kubectl_path_documents" "example" {
  depends_on = [helm_release.ingress_nginx]
  pattern = "${path.module}/assets/example.yaml"
  vars = {
    example_host = "${var.example_host}.${helm_release.ingress_nginx.load_balancer.ip}.nip.io"
    # example_host = var.example_host
    env_name  = var.env_name
  }
}
```
 
Could you tell me, if this is possible with your setup? I'm trying to find out the attributes of the ressource, but didn't find anything appropriate.

Thanks for the good work & Cheers

**Comment by displague** [comment]
Hi @derrabauke,

The purpose of `example_host` is to demonstrate that the Ingress works and configures DNS (via ExternalDNS and Linode) and configures TLS via CertManager.

I haven't looked at `nip.io` before, but they appear to offer DNS names based on IP address (inclusion in the name), so you wouldn't need ExternalDNS for this.  You could try to take advantage of the CertManager integration, but https://nickjanetakis.com/blog/ngrok-lvhme-nipio-a-trilogy-for-local-development-and-testing#nipio suggests that 'prod' certificates are rate-limited.

**Comment by derrabauke** [comment]
Thx for the fast reply!

Actually nip.io was my second shot, since my service which I want to publish was not available after creation...

One more question: With the following ingress definition in `./modules/ingress_nginx/assets/example.yaml`, `example_host=example.com` and a service called todo-app (ClusterIP, different namespace), my service should be available under: `http://example.com`, right?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # NOTE: enable session affinity to make websockets work for deployments with replica > 1
    nginx.ingress.kubernetes.io/affinity: 'cookie'
    nginx.ingress.kubernetes.io/session-cookie-name: 'express_sid'
    cert-manager.io/cluster-issuer: letsencrypt-${env_name}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    use-proxy-protocol: "true"
  name: app-ingress
  namespace: ingress-nginx
spec:
  rules:
  - host: ${example_host}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app
            port:
              number: 80
  tls:
  - hosts:
    - ${example_host}
    secretName: ${example_host}-crt
```

Sorry for bothering you with that, but I really want to understand it.
